image: node:lts-alpine

cache:
  paths:
    - "~/.npm"

before_script:
  - npm install hexo-cli -g
  - npm ci

test:
  script:
    - npm run build
  except:
    - main

pages:
  script:
    - npm run build
    # Compressed assets
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - main