name: github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore last modified time
      run: "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Dependencies
      uses: actions/cache@v2.1.4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install pandoc via micromamba
      run: |
        wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj ./micromamba --strip-components=1
        ./micromamba create -p ~/pandoc pandoc -c conda-forge 
        ./micromamba activate ~/pandoc
    - name: Build website
      run: npm ci && npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        full_commit_message: ${{ github.event.head_commit.message }}
