name: Check markdown links (Lychee)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # Every Monday

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        id: lychee
        with:
          fail: true
          args: '--accept 200,204,429 --verbose --no-progress --cache --max-cache-age 1d source/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
