name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build website
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Restore last modified time
      run: "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Dependencies
      uses: actions/cache@v2.1.4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install pandoc via micromamba
      run: |
        wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvjC /tmp --strip-components=1
        /tmp/micromamba create -p $HOME/pkg pandoc -c conda-forge
        echo "$HOME/pkg/bin" >> $GITHUB_PATH
    - name: Build website
      run: npm ci && npm run build
